base_dir: "."

paths:
  # Model Weights
  transformer_model: "models/transformer/waray_tagalog_transformer_model.pt"
  tokenizer_model: "models/transformer/tokenizer/waray_tagalog_bpe.model"
  
  # Datasets
  json_data: "data/processed/waray/tokenized_waray_tagalog.jsonl"
  csv_data: "data/processed/waray/translation_pairs_waray_tagalog.csv"